<?php 
	$previousUrl = $this->url('master').'/departments/index';
	$nextUrl = $this->url('master').'/departments/edit/'.$data['id'];
?>
<ol id="plist" class="clearfix">
	<li><a href=<?php echo $this->url('application') ?> >トップページ</a></li>
	
	<li><a href="<?php echo $previousUrl ?>">部門一覧</a></li>
	<li><span>部門詳細</span></li>
</ol>

<table class="tbl_type01 mb1e w100">
	<tr>
		<th class="w25">部門コード</th>
		<td class="w75"><?php echo $data['post_cd']; ?></td>
	</tr>
	<tr>
		<th>部門名</th>
		<td><?php echo $data['post_name']; ?></td>
	</tr>
	<tr>
		<th>カタカナ</th>
		<td><?php echo $data['post_kane']; ?></td>
	</tr>
	</table>

<div class="ta_c">
	<button onclick="location.href='<?php echo $previousUrl ;?>'" >戻る</button>
	<button onclick="location.href='<?php echo $nextUrl ;?>'">編集</button>
</div>