<?php echo $this->doctype(); ?>

<html lang="ja" class="no-js">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale = 1.0, user-scalable = no">
        <title>C Side</title>
        <!--<meta charset="utf-8">-->
        <?php //echo $this->headTitle('cside')->setAutoEscape(false) ?>

        <?php //echo $this->headMeta()
            //->appendName('viewport', 'width=device-width, initial-scale=1.0')
            //->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                       // ->prependStylesheet($this->basePath('css/style.css'))
                        //->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        //->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/default.css')) ?>

        <!-- Scripts -->
        <?php //echo $this->headScript()
            //->prependFile($this->basePath('js/bootstrap.min.js'))
            //->prependFile($this->basePath('js/jquery.min.js'))
            //->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
           // ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>


                        <?php echo $this->content; ?>

    </body>
</html>
